### ISSUE TITLE
Concurrent User Calculations

### ISSUE THREAD

**Issue by DanRunfola** [itpir/extract-scripts#21]
Seth -

For our long-term vision of this repository (daily NDVI extracts with masks done via arbitrary polygons at a global scale!; KFW grid-level extracts!; etc.), we need to estimate how many concurrent jobs we could run per new node on SciClone (in order to cost out how much hardware we need to buy based on our anticipated user base).

I.e., a report that would be helpful would be to start with 10 hypothetical users:
(A) Given our current tech infrastructure, how many concurrent jobs we can run (i.e., one :) ), and so how long it would take 10 users to do three flavors of extracts: (1) the simple ones where we define admin zones and limit to years; (2) slightly more complex ones where they can define shapefile inputs (think KFW grids); (3) crazy ones where you get to select days and can also do world-bank style shapes.

(B) For those same 10 users and those 3 scenarios, what is the relationship between processing time (y axis) and number of nodes we could buy from sciclone (x axis)?

**Comment by sgoodm** [comment]
done. included in #22
